### ISSUE TITLE
an implementation is missing

### ISSUE THREAD

**Issue by dsshove** [kaitai-io/kaitai_struct_cpp_stl_runtime#23]
Hi,
I am getting this message when using repeat:eos:
`
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
	at io.kaitai.struct.languages.components.EveryReadIsExpression.handleAssignmentTempVar(EveryReadIsExpression.scala:200)
	at io.kaitai.struct.languages.components.EveryReadIsExpression.handleAssignmentTempVar$(EveryReadIsExpression.scala:200)
	at io.kaitai.struct.languages.CppCompiler.handleAssignmentTempVar(CppCompiler.scala:14)
	at io.kaitai.struct.languages.components.EveryReadIsExpression.attrUserTypeParse(EveryReadIsExpression.scala:147)
	at io.kaitai.struct.languages.components.EveryReadIsExpression.attrUserTypeParse$(EveryReadIsExpression.scala:107)
	at io.kaitai.struct.languages.CppCompiler.attrUserTypeParse(CppCompiler.scala:14)
	at io.kaitai.struct.languages.components.EveryReadIsExpression.attrParse2(EveryReadIsExpression.scala:43)
	at io.kaitai.struct.languages.components.EveryReadIsExpression.attrParse2$(EveryReadIsExpression.scala:24)
	at io.kaitai.struct.languages.CppCompiler.attrParse2(CppCompiler.scala:14)
	at io.kaitai.struct.languages.components.CommonReads.attrParse0(CommonReads.scala:64)
	at io.kaitai.struct.languages.components.CommonReads.attrParse0$(CommonReads.scala:60)
	at io.kaitai.struct.languages.CppCompiler.attrParse0(CppCompiler.scala:14)
	at io.kaitai.struct.languages.components.CommonReads.attrParse(CommonReads.scala:41)
	at io.kaitai.struct.languages.components.CommonReads.attrParse$(CommonReads.scala:11)
	at io.kaitai.struct.languages.CppCompiler.attrParse(CppCompiler.scala:14)
	at io.kaitai.struct.ClassCompiler.$anonfun$compileSeq$1(ClassCompiler.scala:226)
	at io.kaitai.struct.ClassCompiler.$anonfun$compileSeq$1$adapted(ClassCompiler.scala:222)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at io.kaitai.struct.ClassCompiler.compileSeq(ClassCompiler.scala:222)
	at io.kaitai.struct.ClassCompiler.compileSeqProc(ClassCompiler.scala:210)
	at io.kaitai.struct.ClassCompiler.compileEagerRead(ClassCompiler.scala:172)
	at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:71)
	at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:25)
	at io.kaitai.struct.Main$.compile(Main.scala:65)
	at io.kaitai.struct.JavaMain.compileSpecAndWriteToFile(JavaMain.scala:282)
	at io.kaitai.struct.JavaMain.$anonfun$compileOneLang$2(JavaMain.scala:265)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at io.kaitai.struct.JavaMain.compileOneLang(JavaMain.scala:263)
	at io.kaitai.struct.JavaMain.compileOneInput(JavaMain.scala:242)
	at io.kaitai.struct.JavaMain.$anonfun$run$1(JavaMain.scala:212)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at io.kaitai.struct.JavaMain.run(JavaMain.scala:210)
	at io.kaitai.struct.JavaMain$.main(JavaMain.scala:201)
	at io.kaitai.struct.JavaMain.main(JavaMain.scala)
`

Here is the .ksy file I'm passing to the compiler
```
meta:
   id: myfileformat
   endian: le
seq:
   -
      id: mysignature
      contents: [0x12, 0x34, 0x56, 0x78]
   -
      id: content_length
      type: u4
   -
      id: file_entries
      type: file_entry
      repeat: eos
types:
   file_entry:
      seq:
         -
            id: name_length
            type: u4
         -
            id: name
            size: name_length
instances:
  content_length_remaining:
    value: content_length - 8
```

Please let me know if I may provide additional information that may be useful in tracking down or resolving the issue.  I haven' t dug too deep into the compiler Scala code, though I may have time to that this weekend.
